### ISSUE TITLE
思路上的建议，取消CADisplayLink

### ISSUE THREAD

**Issue by bb-coder** [KittenYang/KYCuteView#2]
我fork了你的程序，杨同学，实现的效果很好，但是我发现快速拖动气泡的时候会露出绘制的矩形尖角，导致动画略显粗糙和生硬。这个问题是由于手势拖动和displaylink触发的方法不同步导致的，会延迟矩形的绘制过程。对此我开了一个分支，代码中尝试去掉了CADisplayLink，现在动画更顺
滑了^_^

**Comment by KittenYang** [comment]
感谢！
